### ISSUE TITLE
java.lang.IllegalStateException: destroy must be called on the main UI thread.

### ISSUE THREAD

**Issue by jenzz** [appnexus/mobile-sdk-android#22]
I have spotted the following exception in our error logs:

```
09-13 16:15:08.719 18368-18377 E/System: java.lang.IllegalStateException: destroy must be called on the main UI thread.
                                                                at adn.b(:com.google.android.gms.DynamiteModulesA:251)
                                                                at com.google.android.gms.ads.internal.a.a(:com.google.android.gms.DynamiteModulesA:228)
                                                                at com.google.android.gms.ads.internal.client.ai.onTransact(:com.google.android.gms.DynamiteModulesA:59)
                                                                at android.os.Binder.transact(Binder.java:387)
                                                                at com.google.android.gms.ads.internal.client.zzu$zza$zza.destroy(Unknown Source)
                                                                at com.google.android.gms.ads.internal.client.zzae.destroy(Unknown Source)
                                                                at com.google.android.gms.ads.doubleclick.PublisherAdView.destroy(Unknown Source)
                                                                at com.appnexus.opensdk.mediatedviews.GooglePlayDFPBanner.destroy(GooglePlayDFPBanner.java:93)
                                                                at com.appnexus.opensdk.mediatedviews.DFPBanner.destroy(DFPBanner.java:54)
                                                                at com.appnexus.opensdk.MediatedAdViewController.finishController(MediatedAdViewController.java:191)
                                                                at com.appnexus.opensdk.MediatedAdViewController.cancel(MediatedAdViewController.java:540)
                                                                at com.appnexus.opensdk.AdViewRequestManager.cancel(AdViewRequestManager.java:42)
                                                                at com.appnexus.opensdk.AdFetcher.stop(AdFetcher.java:70)
                                                                at com.appnexus.opensdk.AdView.finalize(AdView.java:311)
                                                                at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:202)
                                                                at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:185)
                                                                at java.lang.Thread.run(Thread.java:818)
```

The problem seems to be that the [AdView](https://github.com/appnexus/mobile-sdk-android/blob/master/sdk/src/com/appnexus/opensdk/AdView.java#L304-L313) class overrides its `finalize()` method to stop the ad fetcher:

```
@Override
protected void finalize() {
  try {
    super.finalize();
  } catch (Throwable e) {}

  // Just in case, kill the adfetcher's service
  if (mAdFetcher != null)
    mAdFetcher.stop();
}
```

The JVM does not guarantee which thread will invoke `finalize()` (see `java.lang.Daemons$FinalizerDaemon` above)
so you would have to ensure you are on the main thread before stopping the ad fetcher.
Or, even better, move it to one of the other, custom lifecycle methods.

**Comment by josecu** [comment]
Thanks, Jens! We'll get that patched up as soon as possible.

Best,
Jose

On Sep 13, 2016, at 11:32 AM, Jens Driller <notifications@github.com<mailto:notifications@github.com>> wrote:


I have spotted the following exception in our error logs:

09-13 16:15:08.719 18368-18377 E/System: java.lang.IllegalStateException: destroy must be called on the main UI thread.
                                                                at adn.b(:com.google.android.gms.DynamiteModulesA:251)
                                                                at com.google.android.gms.ads.internal.a.a(:com.google.android.gms.DynamiteModulesA:228)
                                                                at com.google.android.gms.ads.internal.client.ai.onTransact(:com.google.android.gms.DynamiteModulesA:59)
                                                                at android.os.Binder.transact(Binder.java:387)
                                                                at com.google.android.gms.ads.internal.client.zzu$zza$zza.destroy(Unknown Source)
                                                                at com.google.android.gms.ads.internal.client.zzae.destroy(Unknown Source)
                                                                at com.google.android.gms.ads.doubleclick.PublisherAdView.destroy(Unknown Source)
                                                                at com.appnexus.opensdk.mediatedviews.GooglePlayDFPBanner.destroy(GooglePlayDFPBanner.java:93)
                                                                at com.appnexus.opensdk.mediatedviews.DFPBanner.destroy(DFPBanner.java:54)
                                                                at com.appnexus.opensdk.MediatedAdViewController.finishController(MediatedAdViewController.java:191)
                                                                at com.appnexus.opensdk.MediatedAdViewController.cancel(MediatedAdViewController.java:540)
                                                                at com.appnexus.opensdk.AdViewRequestManager.cancel(AdViewRequestManager.java:42)
                                                                at com.appnexus.opensdk.AdFetcher.stop(AdFetcher.java:70)
                                                                at com.appnexus.opensdk.AdView.finalize(AdView.java:311)
                                                                at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:202)
                                                                at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:185)
                                                                at java.lang.Thread.run(Thread.java:818)


The problem seems to be that the AdView<https://github.com/appnexus/mobile-sdk-android/blob/master/sdk/src/com/appnexus/opensdk/AdView.java#L304-L313> class overrides its finalize() method to stop the ad fetcher:

@Override
protected void finalize() {
  try {
    super.finalize();
  } catch (Throwable e) {}

  // Just in case, kill the adfetcher's service
  if (mAdFetcher != null)
    mAdFetcher.stop();
}


The JVM does not guarantee which thread will invoke finalize() (see java.lang.Daemons$FinalizerDaemon above)
so you would have to ensure you are on the main thread before stopping the ad fetcher.
