### ISSUE TITLE
NullPointerException on AdMobNativeAdResponse.java

### ISSUE THREAD

**Issue by SylvainGourdaut** [appnexus/mobile-sdk-android#27]
I experienced a crash using your SDK (v 2.15.1).

> Fatal Exception: java.lang.NullPointerException
       at com.appnexus.opensdk.mediatednativead.AdMobNativeAdResponse.loadAssets(AdMobNativeAdResponse.java:123)
       at com.appnexus.opensdk.mediatednativead.AdMobNativeAdResponse.<init>(AdMobNativeAdResponse.java:92)
       at com.appnexus.opensdk.mediatednativead.AdMobNativeListener.onAppInstallAdLoaded(AdMobNativeListener.java:59)
       at com.google.android.gms.internal.zzeg.zza(Unknown Source)
       at com.google.android.gms.internal.zzeb$zza.onTransact(Unknown Source)
       at android.os.Binder.transact(Binder.java:361)
       at com.google.android.gms.ads.internal.formats.client.x.a(:com.google.android.gms.DynamiteModulesA:82)
       at com.google.android.gms.ads.internal.ba.run(:com.google.android.gms.DynamiteModulesA:230)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5653)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by sgallo0692** [comment]
Hi @SylvainGourdaut 

Are you able to reproduce this readily? What are steps we can take to reproduce this issue if this is a production app? Otherwise, can you try enabling our SDK's logging feature and providing us with the output from those logs? https://wiki.appnexus.com/display/sdk/Configure+SDK+Logging

Best,
Steve

**Comment by SylvainGourdaut** [comment]
Hi Steve,

I haven't experienced this by myself, it's a log that i get from my tracker (Fabric).

I've tried to reproduce it, but i haven't succeed.

What i can do is to enable the logging, and if i luckily reproduce it someday i will give you the logs.

Best, 
Sylvain

**Comment by Kowshickkarthick** [comment]
HI @SylvainGourdaut,

We were eventually able to replicate this issue.
The fix for this will be part of v5.1 release.
