### ISSUE TITLE
NullPointerException com.iab.omid.library.appnexus.publisher.a

### ISSUE THREAD

**Issue by asalliou** [appnexus/mobile-sdk-android#36]
Hi, I'm experiencing a crash with banners and app nexus android SDK 4.10 : 

Android: 4.3
Android Build: JSS15J.I9300XXUGNJ2
Manufacturer: samsung
Model: GT-I9300
Thread: main-1

```
java.lang.NullPointerException
	at com.iab.omid.library.appnexus.publisher.a.<init>(Unknown Source)
	at com.iab.omid.library.appnexus.adsession.a.<init>(Unknown Source)
	at com.iab.omid.library.appnexus.adsession.AdSession.createAdSession(Unknown Source)
	at com.appnexus.opensdk.viewability.ANOmidBannerHTMLAdSession.initAdSession(ANOmidBannerHTMLAdSession.java:59)
	at com.appnexus.opensdk.AdWebView$AdWebViewClient.onPageFinished(AdWebView.java:396)
	at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:416)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:5419)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by ppuviarasu** [comment]
implemented & released with v4.11.1
