### ISSUE TITLE
Fatal Exception: java.lang.AssertionError No NameTypeIndex match for SHORT_DAYLIGHT com.appnexus.opensdk.utils.Settings.<init>

### ISSUE THREAD

**Issue by Belka1000867** [appnexus/mobile-sdk-android#39]
Hi, I started to get such kind of bugs recently and it looks specific for Android 8.0 only.

Seems it comes from here: 
`SDKSettings.useHttps(true);`

> Fatal Exception: java.lang.AssertionError: No NameTypeIndex match for SHORT_DAYLIGHT
       at android.icu.impl.TimeZoneNamesImpl$ZNames.getNameTypeIndex(TimeZoneNamesImpl.java:724)
       at android.icu.impl.TimeZoneNamesImpl$ZNames.getName(TimeZoneNamesImpl.java:790)
       at android.icu.impl.TimeZoneNamesImpl.getTimeZoneDisplayName(TimeZoneNamesImpl.java:183)
       at android.icu.text.TimeZoneNames.getDisplayName(TimeZoneNames.java:261)
       at java.util.TimeZone.getDisplayName(TimeZone.java:405)
       at java.util.TimeZone.getDisplayName(TimeZone.java:370)
       at com.appnexus.opensdk.utils.Settings.<init>(Settings.java:52)
       at com.appnexus.opensdk.utils.Settings.getSettings(Settings.java:96)
       at com.appnexus.opensdk.SDKSettings.useHttps(SDKSettings.java:167)
       at #############.a.b.<init>(AdService.java:57)
       at #############.b.f(ServiceLocator.java:321)
       at #############.b.a(PresenterFactory.kt:392)
       at #############.b.b.f(ArticleFragment.kt:2132)
       at #############.onStart(PresenterFragment.kt:43)
       at #############.onStart(WebViewPresenterFragment.kt:30)
       at android.support.v4.app.Fragment.performStart(Fragment.java:2372)
       at android.support.v4.app.k.a(FragmentManager.java:1467)
       at android.support.v4.app.k.c(FragmentManager.java:1759)
       at android.support.v4.app.k.a(FragmentManager.java:1827)
       at android.support.v4.app.b.f(BackStackRecord.java:797)
       at android.support.v4.app.k.b(FragmentManager.java:2596)
       at android.support.v4.app.k.a(FragmentManager.java:2383)
       at android.support.v4.app.k.b(FragmentManager.java:2338)
       at android.support.v4.app.k.b(FragmentManager.java:2215)
       at android.support.v4.app.b.e(BackStackRecord.java:649)
       at android.support.v4.app.n.b(FragmentStatePagerAdapter.java:167)
       at android.support.v4.view.ViewPager.a(ViewPager.java:1238)
       at android.support.v4.view.ViewPager.b(ViewPager.java:1086)
       at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
       at android.view.View.measure(View.java:22112)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6613)
       at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:739)
       at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:91)
       at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1361)
       at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:809)
       at android.view.View.measure(View.java:22112)
       at android.widget.RelativeLayout.measureChild(RelativeLayout.java:676)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:479)
       at android.view.View.measure(View.java:22112)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6613)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)
       at android.view.View.measure(View.java:22112)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6613)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
       at android.view.View.measure(View.java:22112)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6613)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:22112)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6613)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
       at android.view.View.measure(View.java:22112)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6613)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at com.android.internal.policy.DecorView.onMeasure(DecorView.java:875)
       at android.view.View.measure(View.java:22112)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2426)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1508)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1765)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1396)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6773)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:974)
       at android.view.Choreographer.doCallbacks(Choreographer.java:786)
       at android.view.Choreographer.doFrame(Choreographer.java:721)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:960)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6501)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by Kowshickkarthick** [comment]
Hi @Belka1000867,

Thanks for pointing this out.
We have fixed this in v5.1.1.

Thanks and BR,
Kowshick S
