### ISSUE TITLE
Android 9 DiskViolation

### ISSUE THREAD

**Issue by omegasoft7** [appnexus/mobile-sdk-android#40]
With Android 9 I see following error:

```D/StrictMode: StrictMode policy violation; ~duration=56 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
        at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:251)
        at java.io.File.exists(File.java:815)
        at android.app.ContextImpl.getDataDir(ContextImpl.java:2253)
        at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:550)
        at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:747)
        at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:400)
        at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:174)
        at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:174)
        at android.preference.PreferenceManager.getDefaultSharedPreferences(PreferenceManager.java:526)
        at com.appnexus.opensdk.AdView.b(AdView.java:116)
        at com.appnexus.opensdk.BannerAdView.b(BannerAdView.java:178)
        at com.appnexus.opensdk.AdView.<init>(AdView.java:100)
        at com.appnexus.opensdk.AdView.<init>(AdView.java:95)
        at com.appnexus.opensdk.AdView.<init>(AdView.java:91)
        at com.appnexus.opensdk.BannerAdView.<init>(BannerAdView.java:121)```

**Comment by Daniel-Berger** [comment]
Hi. Can you please share more context around when and how this error occurred?

**Comment by omegasoft7** [comment]
As long as you are using any version of Android it is working just fine. But when you try to see the ads in a device that has Android 9, then you face an issue that Banner View is not visible anymore and when you check logs you see error message i mentioned earlier.

I tried to debug it a little bit and it seems that the issue is because in `AdView.java:116` you are trying to access `SharedPreferences` while you are in a mainThread and Android 9 is restricted about that and is causing a crash there.

**Comment by avohraa** [comment]
Have you enabled the `StrictMode`? If yes, can you check if it is configured with `penaltyDeath()` in any case? If yes, try using `penaltyLog()` only and check if that resolves the crash along with other issues.

**Comment by omegasoft7** [comment]
@avohraa here is my StrictMode:
``` StrictMode.setThreadPolicy(StrictMode.ThreadPolicy.Builder().detectAll().penaltyLog().build())
        StrictMode.setVmPolicy(StrictMode.VmPolicy.Builder().detectAllExceptSocketTags().penaltyLog().build())```

**Comment by omegasoft7** [comment]
Btw removing those StrictMode configurations did it help resolving the issue

**Comment by avohraa** [comment]
@omegasoft7 I would say that I haven't given a solution to any problem. Instead, I haven't faced the issue while rendering a BannerAd in the Android 9.

Looking at the logs, I tried StrictMode and got the error message but that, in any case, does not crash the app until `penaltyDeath()` is used.

I would recommend if you can try reproducing the crash using [this Sample App](https://play.google.com/store/apps/details?id=com.appnexus.opensdkapp&hl=en_US). And in case you find issues with that, feel free to reach back with the device details. So that we can closely look into this issue.

**Comment by omegasoft7** [comment]
@avohraa Maybe I explained it wrong, it is not crashing the app but it is simply not showing ads. And when you check logs you see the logs that I mentioned here.

Also, it is very obvious that it is violating something and that has to be fixed. changing configs in `StrictMode` cannot be an option for us as the process to get approval for changing it might take several months or our request might fail.
