### ISSUE TITLE
NoClassDefFoundError in 7.5 release

### ISSUE THREAD

**Issue by dpliskov** [appnexus/mobile-sdk-android#50]
After last update the library crashes with error:
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/iab/omid/library/appnexus/Omid;
        at com.appnexus.opensdk.viewability.ANOmidViewabilty.activateOmidAndCreatePartner(ANOmidViewabilty.java:62)
        at com.appnexus.opensdk.AdView.setup(AdView.java:124)
        at com.appnexus.opensdk.BannerAdView.setup(BannerAdView.java:184)
        at com.appnexus.opensdk.AdView.<init>(AdView.java:116)
        at com.appnexus.opensdk.AdView.<init>(AdView.java:111)
        at com.appnexus.opensdk.AdView.<init>(AdView.java:107)
        at com.appnexus.opensdk.BannerAdView.<init>(BannerAdView.java:126)

Setting the versions to 7.4.1 helps.

We use:
com.appnexus.opensdk:appnexus-sdk
com.appnexus.opensdk.mediatedviews:appnexus-googleplay-mediation

**Comment by Kowshickkarthick** [comment]
Hi @dpliskov 

Thanks for reporting this.
We have identified the root cause to be with the Maven Plugin used to upload our library.
Maven Plugin is not able to upload  *.aar  dependencies correctly.

We are working on a fix for this.

**Comment by avohraa** [comment]
Hi @dpliskov 

The fix for it is out -> [v7.5.1](https://github.com/appnexus/mobile-sdk-android/releases/tag/7.5.1)

**Comment by dpliskov** [comment]
Works well now, thanks!
