### ISSUE TITLE
PlacementID parsing crash

### ISSUE THREAD

**Issue by ScottCheckoSGI** [appnexus/mobile-sdk-android#77]
Using Android client version 8.1 of Xandr, there is a crash when parsing alphanumeric placement IDs. There is no crash on the iOS client 8.1.1 using similarly formatted IDs. The format of the placement ids used without giving them out on android is "XXXXXXAND1", and the iOS versions are "XXXXXXiOS1". The number at the end changes for each placement size supported for a total of 3 placement ids per platform. When the ids on android are replaced with fully numeric values, the crash does not occur however the error referenced in issue https://github.com/appnexus/mobile-sdk-ios/issues/81 does continue to occur.

We are creating a non-native, non-lazy banner ad following the samples as closely as possible:

```
private BannerAdView createBanner( final String placementId, float width, float height )
{
BannerAdView banner = new BannerAdView( m_activity );

Resources r = m_activity.getResources();
m_bannerWidth = TypedValue.applyDimension( TypedValue.COMPLEX_UNIT_DIP, width, r.getDisplayMetrics() );
m_bannerHeight = TypedValue.applyDimension( TypedValue.COMPLEX_UNIT_DIP, height, r.getDisplayMetrics() );
Logger.i( "XandrStaticAd::createBanner -- creating banner ad with <w:" + width + ", h:" + height + ", xdim:" + m_bannerWidth + ", ydim:" + m_bannerHeight + ">, placement: " + placementId );
banner.setLayoutParams( new FrameLayout.LayoutParams( Math.round( m_bannerWidth ), Math.round( m_bannerHeight ) ) );
banner.setAdSize( ( int )width, ( int )height );

banner.setPlacementID( placementId );
banner.setAdListener( createAdListener() );

return banner;
}

```

Here are the resulting logs with a callstack of the crash:

```
11-10 10:37:18.202 18923 18991 I app_process: [  35.436] JNI Method: className [com.company.app.xandr.XandrStaticAd], methodName [setAdVisibility], methodSignature [(Z)V]
11-10 10:37:18.220 18923 18923 I app_process: [  35.453] XandrStaticAd::createBanner -- creating banner ad with <w:320.0, h:50.0, xdim:880.0, ydim:137.5>, placement: XXXXXXAND1
11-10 10:37:18.222 18923 18923 I app_process: [  35.455] XandrStaticAd::createAd -- Successfully created banner, loading ad.
11-10 10:37:18.222 18923 18923 I app_process: [  35.456] XandrStaticAd::createAd --  placemenent: [XXXXXXAND1]
11-10 10:37:18.227 18923 18923 I app_process: [  35.460] XandrStaticAd::positionAd -- positioning ad at <x:540.0 , y:68.74988>
11-10 10:37:18.227 18923 18923 I app_process: [  35.460] XandrStaticAd::setAdVisibility -- setting ad visibility to: true
11-10 10:37:18.242 18923 19034 E OPENSDK : Exception while parsing integer value from string: XXXXXXAND1 - For input string: "XXXXXXAND1"
11-10 10:37:18.242 18923 19034 E OPENSDK : java.lang.NumberFormatException: For input string: "MAHMOBAND1"
11-10 10:37:18.242 18923 19034 E OPENSDK :  at java.lang.Integer.parseInt(Integer.java:615)
11-10 10:37:18.242 18923 19034 E OPENSDK :  at java.lang.Integer.parseInt(Integer.java:650)
11-10 10:37:18.242 18923 19034 E OPENSDK :  at com.appnexus.opensdk.utils.StringUtil.getIntegerValue(StringUtil.java:58)
11-10 10:37:18.242 18923 19034 E OPENSDK :  at com.appnexus.opensdk.ut.UTRequestParameters.getTagsObject(UTRequestParameters.java:636)
11-10 10:37:18.242 18923 19034 E OPENSDK :  at com.appnexus.opensdk.ut.UTRequestParameters.getPostData(UTRequestParameters.java:481)
11-10 10:37:18.242 18923 19034 E OPENSDK :  at com.appnexus.opensdk.ut.UTAdRequest.makeRequest(UTAdRequest.java:168)
11-10 10:37:18.242 18923 19034 E OPENSDK :  at com.appnexus.opensdk.ut.UTAdRequest$AsyncRequest.doInBackground(UTAdRequest.java:253)
11-10 10:37:18.242 18923 19034 E OPENSDK :  at com.appnexus.opensdk.ut.UTAdRequest$AsyncRequest.doInBackground(UTAdRequest.java:248)
11-10 10:37:18.242 18923 19034 E OPENSDK :  at android.os.AsyncTask$3.call(AsyncTask.java:394)
11-10 10:37:18.242 18923 19034 E OPENSDK :  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11-10 10:37:18.242 18923 19034 E OPENSDK :  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-10 10:37:18.242 18923 19034 E OPENSDK :  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-10 10:37:18.242 18923 19034 E OPENSDK :  at java.lang.Thread.run(Thread.java:923)
11-10 10:37:18.244 18923 19034 W OPENSDK : Location permissions ACCESS_COARSE_LOCATION and/or ACCESS_FINE_LOCATION are not set in the host app. This may affect demand.
11-10 10:37:18.246 18923 19034 I OPENSDK-REQUEST: POST data: {"tags":[{"id":0,"uuid":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","primary_size":{"width":320,"height":50},"sizes":[{"width":320,"height":50}],"allow_smaller_sizes":false,"banner_frameworks":[6],"allowed_media_types":[1],"prebid":false,"disable_psa":true,"require_asset_url":false}],"user":{"gender":0,"language":"en"},"device":{"make":"Google","model":"sdk_gphone_x86","useragent":"Mozilla\/5.0 (Linux; Android 11; sdk_gphone_x86 Build\/RSR1.201013.001; wv) AppleWebKit\/537.36 (KHTML, like Gecko) Version\/4.0 Chrome\/104.0.5112.97 Mobile Safari\/537.36","mnc":260,"mcc":310,"carrier":"Android","connectiontype":1,"devtime":1668105438245,"limit_ad_tracking":false,"device_id":{"aaid":"xxxxexxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"},"os":"android"},"app":{"appid":"com.company.game"},"sdkver":"ansdk8.1","sdk":{"source":"ansdk","version":"8.1"},"supply_type":"mobile_app","gdpr_consent":{"consent_required":false,"consent_string":""},"iab_support":{"omidpn":"Appnexus","omidpv":"8.1"}}
11-10 10:37:18.532 18923 19034 I OPENSDK-RESPONSE: RESPONSE - {"error":"Could not find valid member in request"}
11-10 10:37:18.538 18923 18923 W OPENSDK-RESPONSE: The server responded, but didn't return any ads.
11-10 10:37:18.538 18923 18923 E OPENSDK : UNABLE_TO_FILL
11-10 10:37:18.542 18923 18923 I app_proce
```

The logs snippet have been censored a bit, let me know if any more information is needed.

**Comment by Kowshickkarthick** [comment]
Hi... @ScottCheckoSGI
Placement Id is always a number. (and is autogenerated)
Inventory code is Alphanumeric string. (chosen/set by your AdOps team)

By looking at your logs, it looks like you are intending to use inventory code and member_id for your BannerAdview.
Can you try using the below API :
`banner.setInventoryCodeAndMemberID();`

**Comment by ScottCheckoSGI** [comment]
Thank you, this makes a lot of sense. I will start testing this hopefully later today.
